# Generated by Django 4.1.7 on 2023-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_bookedhotel_bookeduber_driver_hotel_room_uber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Three Start'), (2, 'Four Start'), (3, 'Five Start')], default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 bed'), (2, '2 bed'), (3, '3 bed')], default=1),
        ),
    ]
