# Generated by Django 4.1.7 on 2023-03-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_hotel_stars_room_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.PositiveSmallIntegerField(choices=[(1, 'RwandAir'), (2, 'KenyanAir Ways'), (3, 'EthiopianAir Ways'), (4, 'EthiopianAir Ways'), (5, 'EthiopianAir Ways'), (6, 'EthiopianAir Ways')], default=1)),
                ('travelway', models.PositiveSmallIntegerField(choices=[(1, 'one way'), (2, 'Two Ways')], default=1)),
                ('names', models.CharField(max_length=300)),
                ('passport', models.IntegerField()),
                ('classplane', models.PositiveSmallIntegerField(choices=[(1, 'Business Class'), (2, 'Economy Class')], default=1)),
                ('Airport_departure', models.CharField(max_length=200)),
                ('location_arrival', models.CharField(max_length=200)),
                ('payment_info', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='price_choices',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 bed/hour=100000'), (2, '2 bed/hour=200000'), (3, '3 bed/hour=300000')], default=1),
        ),
    ]
