# Generated by Django 4.1.7 on 2023-03-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_plane_alter_room_price_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='thumbnail',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
