# Generated by Django 4.1.7 on 2023-03-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_hotel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='src.hotel'),
        ),
    ]
