# Generated by Django 4.1.7 on 2023-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_hotel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetype',
            name='certificate',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
